// Generated by https://quicktype.io

export interface Product {
  id: number
  name: string
  image: string
  price: number
  stock: number
  createdAt: string
  updatedAt: string
}

export interface StockCardInterface {
  title: string
  amount: number
  icon: string
  color: string
}